version: '3.7'
services:
  frontend:
    container_name: front
    build: 
      context: ./site
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./site:/app
  web:
    image: nginx:latest    
    ports:
      - '8000:80'
    volumes:
      - ./api:/var/www/html
      - ./api/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    container_name: api
    build: 
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/html